### ISSUE TITLE
pippo-controller: there is no way to specify alternative file parameter name

### ISSUE THREAD

**Issue by whyicantusemyemailasusername** [pippo-java/pippo#531]
Here the example from pippo.ro site:
```java
@POST("/upload")
@Produces(Produces.TEXT)
public String upload(FileItem file) {..}
```
This code works on java 8+, and only if parameter names are enabled (-parameters argument). There is no way to specify alternative name like one can do for request parameters via @Param("uploaded-file") annotation.

I can think on multiple ways to fix this:
1. Introduce another annotation and use it for such cases (@Multipart("file-name") for example)
1. Introduce method-agnostic way to declare parameter name, like @Named("file-name"), and put name-resolution logic into MethodParameter class.
1. Document such behaviour as "by design"

What do you think?

**Comment by mhagnumdw** [comment]
Hi!

I took a look. The way to retrieve the parameter name in the [FileItemExtractor](https://github.com/pippo-java/pippo/blob/53123a8d6d27780bf3acb0e03d9a7f86ea61464d/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/extractor/FileItemExtractor.java#L36) class is incomplete. This way of retrieving, for example, is ok in the [ParamExtractor](https://github.com/pippo-java/pippo/blob/53123a8d6d27780bf3acb0e03d9a7f86ea61464d/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/extractor/ParamExtractor.java#L43-L44) class.

I'm already preparing a pull request. I did some local tests on the two approaches below and everything was fine:

```java
@POST("/uploadAvatar")
public void uploadAvatar(@Param("fileAvatar") FileItem file) {
    // file is not null \o/
}
```

```java
@POST("/uploadAvatar")
public void uploadAvatar() {
    final FileItem file = getRouteContext().getRequest().getFile("fileAvatar");
    // file is not null, but it already works ;)
}
```

I'll just look at the code a little more because there is a duplication of code, more specifically in the `getParameterName` method, in these places:

- [HeaderExtractor.getParameterName](https://github.com/pippo-java/pippo/blob/53123a8d6d27780bf3acb0e03d9a7f86ea61464d/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/extractor/HeaderExtractor.java#L60-L73)
- [ParamExtractor.getParameterName](https://github.com/pippo-java/pippo/blob/53123a8d6d27780bf3acb0e03d9a7f86ea61464d/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/extractor/ParamExtractor.java#L60-L73)
- [SessionExtractor.getParameterName](https://github.com/pippo-java/pippo/blob/53123a8d6d27780bf3acb0e03d9a7f86ea61464d/pippo-controller-parent/pippo-controller/src/main/java/ro/pippo/controller/extractor/SessionExtractor.java#L45-L58)
- FileItemExtractor.getParameterName (this is new, not yet in Pippo code)

**Comment by decebals** [comment]
@mhagnumdw 
> I'll just look at the code a little more because there is a duplication of code, more specifically in the getParameterName method

What about to extract `getParameterName` method as static method in `MethodParameterExtractor` interface?

By the way, thanks for the initiative and involvement!

**Comment by mhagnumdw** [comment]
@decebals 

> What about to extract getParameterName method as static method in MethodParameterExtractor interface?

But the annotation is of different types:

HeaderExtractor >> getParameterName(MethodParameter parameter, **Header** annotation)
ParamExtractor >> getParameterName(MethodParameter parameter, **Param** annotation)
SessionExtractor >> getParameterName(MethodParameter parameter, **Session** annotation)

Perhaps each Extractor will still have the `getParameterName` method just to extract the `.value()` from annotation and then forward the call to the static interface method.

Maybe I missed something you wanted to tell me.

> By the way, thanks for the initiative and involvement!

It is always good to contribute to Pippo! :)

**Comment by decebals** [comment]
@mhagnumdw 
> But the annotation is of different types

My mistake. Sorry
