### ISSUE TITLE
How to disable HTTP keep-alive timeout? 

### ISSUE THREAD

**Issue by deepakmn** [pippo-java/pippo#573]
I'm using TJWS with Pippo 1.12.0. How to disable HTTP keep-alive timeout and keep the connection?

**Comment by decebals** [comment]
Sorry, I don't use anymore TJWS in my projects. It's an issue (https://github.com/pippo-java/pippo/issues/512) that proposes to remove TJWS from the next major version of Pippo.
TJWS is very light but buggy (my opinion). I think that you can take a look in the code source of TJWS, maybe you will find something useful in configuration.

**Comment by decebals** [comment]
Any resolution here?

**Comment by decebals** [comment]
We [decided](https://github.com/pippo-java/pippo/issues/512) to remove completely teh support for TJWS. The reason is that TJWS is based on Servlet 2 and it's not active maintained. Please switch to other server supported built in in PIppo (Jetty, Tomcat, Undertow) or copy the old tiny `TjwsServer.java` directly in your project.
Thanks for understanding!
